import { FoodItem } from '../types';

export const CATEGORIES = [
  'All',
  'Breakfast',
  'Proteins',
  'Carbs & Grains',
  'Vegetables',
  'Fruits',
  'Dairy & Snacks',
  'Meals',
] as const;

export type FoodCategory = (typeof CATEGORIES)[number];

export const FOOD_DATABASE: FoodItem[] = [
  // ── Breakfast ─────────────────────────────────────────────────────────────
  { id: 'b1',  name: 'Eggs (2 large)',         category: 'Breakfast', calories: 143, protein: 12, carbs: 1,  fat: 10,  serving: '2 eggs' },
  { id: 'b2',  name: 'Oatmeal',                category: 'Breakfast', calories: 147, protein: 5,  carbs: 25, fat: 3,   serving: '1 cup cooked' },
  { id: 'b3',  name: 'Greek Yogurt',           category: 'Breakfast', calories: 130, protein: 17, carbs: 9,  fat: 4,   serving: '1 cup' },
  { id: 'b4',  name: 'Whole Wheat Toast',      category: 'Breakfast', calories: 80,  protein: 4,  carbs: 15, fat: 1,   serving: '1 slice' },
  { id: 'b5',  name: 'Protein Shake',          category: 'Breakfast', calories: 150, protein: 25, carbs: 8,  fat: 3,   serving: '1 scoop' },
  { id: 'b6',  name: 'Pancakes',               category: 'Breakfast', calories: 175, protein: 5,  carbs: 28, fat: 5,   serving: '2 medium' },
  { id: 'b7',  name: 'Granola',                category: 'Breakfast', calories: 120, protein: 3,  carbs: 20, fat: 4,   serving: '¼ cup' },
  { id: 'b8',  name: 'Cottage Cheese',         category: 'Breakfast', calories: 110, protein: 13, carbs: 4,  fat: 5,   serving: '½ cup' },
  { id: 'b9',  name: 'Bagel',                  category: 'Breakfast', calories: 270, protein: 11, carbs: 55, fat: 2,   serving: '1 medium' },
  { id: 'b10', name: 'Smoothie Bowl',          category: 'Breakfast', calories: 350, protein: 10, carbs: 55, fat: 10,  serving: '1 bowl' },
  { id: 'b11', name: 'Avocado Toast',          category: 'Breakfast', calories: 220, protein: 6,  carbs: 22, fat: 13,  serving: '1 slice' },
  { id: 'b12', name: 'Banana Pancakes',        category: 'Breakfast', calories: 190, protein: 6,  carbs: 32, fat: 5,   serving: '2 pancakes' },
  { id: 'b13', name: 'French Toast',           category: 'Breakfast', calories: 300, protein: 10, carbs: 40, fat: 10,  serving: '2 slices' },
  { id: 'b14', name: 'Waffles',                category: 'Breakfast', calories: 310, protein: 8,  carbs: 42, fat: 13,  serving: '2 medium' },
  { id: 'b15', name: 'Overnight Oats',         category: 'Breakfast', calories: 300, protein: 12, carbs: 45, fat: 8,   serving: '1 cup' },
  { id: 'b16', name: 'Chia Pudding',           category: 'Breakfast', calories: 200, protein: 8,  carbs: 20, fat: 11,  serving: '½ cup' },
  { id: 'b17', name: 'English Muffin',         category: 'Breakfast', calories: 134, protein: 5,  carbs: 26, fat: 1,   serving: '1 muffin' },
  { id: 'b18', name: 'Corn Flakes',            category: 'Breakfast', calories: 100, protein: 2,  carbs: 24, fat: 0,   serving: '1 cup' },
  { id: 'b19', name: 'Acai Bowl',              category: 'Breakfast', calories: 400, protein: 8,  carbs: 60, fat: 15,  serving: '1 bowl' },
  { id: 'b20', name: 'Breakfast Burrito',      category: 'Breakfast', calories: 380, protein: 20, carbs: 40, fat: 15,  serving: '1 burrito' },
  { id: 'b21', name: 'Croissant',              category: 'Breakfast', calories: 272, protein: 5,  carbs: 31, fat: 14,  serving: '1 medium' },
  { id: 'b22', name: 'Blueberry Muffin',       category: 'Breakfast', calories: 315, protein: 4,  carbs: 54, fat: 10,  serving: '1 medium' },
  { id: 'b23', name: 'Turkey Bacon',           category: 'Breakfast', calories: 70,  protein: 8,  carbs: 1,  fat: 4,   serving: '2 strips' },
  { id: 'b24', name: 'Breakfast Sausage',      category: 'Breakfast', calories: 170, protein: 7,  carbs: 1,  fat: 15,  serving: '2 links' },
  { id: 'b25', name: 'Smoked Salmon',          category: 'Breakfast', calories: 66,  protein: 10, carbs: 0,  fat: 3,   serving: '2 oz' },
  { id: 'b26', name: 'Cream Cheese',           category: 'Breakfast', calories: 102, protein: 2,  carbs: 1,  fat: 10,  serving: '2 tbsp' },
  { id: 'b27', name: 'Almond Butter Toast',    category: 'Breakfast', calories: 230, protein: 7,  carbs: 21, fat: 14,  serving: '1 slice' },
  { id: 'b28', name: 'Hash Browns',            category: 'Breakfast', calories: 130, protein: 2,  carbs: 18, fat: 6,   serving: '½ cup' },
  { id: 'b29', name: 'Crepes (2)',             category: 'Breakfast', calories: 200, protein: 7,  carbs: 26, fat: 8,   serving: '2 crepes' },
  { id: 'b30', name: 'Porridge',               category: 'Breakfast', calories: 166, protein: 6,  carbs: 28, fat: 4,   serving: '1 cup' },
  { id: 'b31', name: 'Skyr',                   category: 'Breakfast', calories: 130, protein: 23, carbs: 8,  fat: 0,   serving: '1 cup' },
  { id: 'b32', name: 'Protein Oatmeal',        category: 'Breakfast', calories: 250, protein: 20, carbs: 30, fat: 5,   serving: '1 cup' },
  { id: 'b33', name: 'Fruit & Nut Bar',        category: 'Breakfast', calories: 200, protein: 5,  carbs: 28, fat: 8,   serving: '1 bar' },
  { id: 'b34', name: 'Egg McMuffin (style)',   category: 'Breakfast', calories: 290, protein: 17, carbs: 30, fat: 12,  serving: '1 sandwich' },
  { id: 'b35', name: 'Cereal (bran flakes)',   category: 'Breakfast', calories: 127, protein: 4,  carbs: 31, fat: 1,   serving: '¾ cup' },
  { id: 'b36', name: 'Belgian Waffle',         category: 'Breakfast', calories: 400, protein: 10, carbs: 55, fat: 16,  serving: '1 large' },
  { id: 'b37', name: 'Quiche Slice',           category: 'Breakfast', calories: 310, protein: 14, carbs: 20, fat: 19,  serving: '1 slice' },
  { id: 'b38', name: 'Peanut Butter Banana',   category: 'Breakfast', calories: 280, protein: 8,  carbs: 38, fat: 12,  serving: '1 serving' },
  { id: 'b39', name: 'Açaí Smoothie',          category: 'Breakfast', calories: 220, protein: 4,  carbs: 40, fat: 5,   serving: '12 oz' },
  { id: 'b40', name: 'Frittata (2 eggs)',      category: 'Breakfast', calories: 185, protein: 14, carbs: 5,  fat: 12,  serving: '1 serving' },

  // ── Proteins ───────────────────────────────────────────────────────────────
  { id: 'p1',  name: 'Chicken Breast',         category: 'Proteins',  calories: 165, protein: 31, carbs: 0,  fat: 4,   serving: '100g' },
  { id: 'p2',  name: 'Salmon',                 category: 'Proteins',  calories: 208, protein: 20, carbs: 0,  fat: 13,  serving: '100g' },
  { id: 'p3',  name: 'Tuna (canned)',          category: 'Proteins',  calories: 130, protein: 28, carbs: 0,  fat: 1,   serving: '100g' },
  { id: 'p4',  name: 'Turkey Breast',          category: 'Proteins',  calories: 135, protein: 30, carbs: 0,  fat: 1,   serving: '100g' },
  { id: 'p5',  name: 'Shrimp',                 category: 'Proteins',  calories: 99,  protein: 24, carbs: 0,  fat: 0,   serving: '100g' },
  { id: 'p6',  name: 'Steak (sirloin)',        category: 'Proteins',  calories: 250, protein: 26, carbs: 0,  fat: 15,  serving: '100g' },
  { id: 'p7',  name: 'Tofu',                   category: 'Proteins',  calories: 76,  protein: 8,  carbs: 2,  fat: 4,   serving: '100g' },
  { id: 'p8',  name: 'Tempeh',                 category: 'Proteins',  calories: 193, protein: 19, carbs: 9,  fat: 11,  serving: '100g' },
  { id: 'p9',  name: 'Black Beans',            category: 'Proteins',  calories: 114, protein: 8,  carbs: 20, fat: 1,   serving: '½ cup' },
  { id: 'p10', name: 'Lentils',                category: 'Proteins',  calories: 115, protein: 9,  carbs: 20, fat: 0,   serving: '½ cup' },
  { id: 'p11', name: 'Cod',                    category: 'Proteins',  calories: 82,  protein: 18, carbs: 0,  fat: 1,   serving: '100g' },
  { id: 'p12', name: 'Egg Whites (3)',         category: 'Proteins',  calories: 51,  protein: 11, carbs: 1,  fat: 0,   serving: '3 whites' },
  { id: 'p13', name: 'Chicken Thigh',          category: 'Proteins',  calories: 209, protein: 26, carbs: 0,  fat: 11,  serving: '100g' },
  { id: 'p14', name: 'Ground Beef (lean)',     category: 'Proteins',  calories: 218, protein: 26, carbs: 0,  fat: 12,  serving: '100g' },
  { id: 'p15', name: 'Pork Tenderloin',        category: 'Proteins',  calories: 143, protein: 26, carbs: 0,  fat: 4,   serving: '100g' },
  { id: 'p16', name: 'Tilapia',                category: 'Proteins',  calories: 128, protein: 26, carbs: 0,  fat: 3,   serving: '100g' },
  { id: 'p17', name: 'Edamame',                category: 'Proteins',  calories: 94,  protein: 9,  carbs: 7,  fat: 4,   serving: '½ cup' },
  { id: 'p18', name: 'Chickpeas',              category: 'Proteins',  calories: 134, protein: 7,  carbs: 22, fat: 2,   serving: '½ cup' },
  { id: 'p19', name: 'Sardines (canned)',      category: 'Proteins',  calories: 177, protein: 21, carbs: 0,  fat: 10,  serving: '85g' },
  { id: 'p20', name: 'Beef Jerky',             category: 'Proteins',  calories: 116, protein: 9,  carbs: 3,  fat: 7,   serving: '1 oz' },
  { id: 'p21', name: 'Lamb Chop',              category: 'Proteins',  calories: 294, protein: 25, carbs: 0,  fat: 21,  serving: '100g' },
  { id: 'p22', name: 'Duck Breast',            category: 'Proteins',  calories: 201, protein: 28, carbs: 0,  fat: 10,  serving: '100g' },
  { id: 'p23', name: 'Ground Turkey',          category: 'Proteins',  calories: 170, protein: 22, carbs: 0,  fat: 9,   serving: '100g' },
  { id: 'p24', name: 'Pork Chop',              category: 'Proteins',  calories: 231, protein: 25, carbs: 0,  fat: 14,  serving: '100g' },
  { id: 'p25', name: 'Halibut',                category: 'Proteins',  calories: 111, protein: 23, carbs: 0,  fat: 2,   serving: '100g' },
  { id: 'p26', name: 'Scallops',               category: 'Proteins',  calories: 111, protein: 20, carbs: 5,  fat: 1,   serving: '100g' },
  { id: 'p27', name: 'Crab',                   category: 'Proteins',  calories: 82,  protein: 18, carbs: 0,  fat: 1,   serving: '100g' },
  { id: 'p28', name: 'Mussels',                category: 'Proteins',  calories: 86,  protein: 12, carbs: 4,  fat: 2,   serving: '100g' },
  { id: 'p29', name: 'Trout',                  category: 'Proteins',  calories: 148, protein: 21, carbs: 0,  fat: 7,   serving: '100g' },
  { id: 'p30', name: 'Mackerel',               category: 'Proteins',  calories: 205, protein: 19, carbs: 0,  fat: 14,  serving: '100g' },
  { id: 'p31', name: 'Kidney Beans',           category: 'Proteins',  calories: 112, protein: 8,  carbs: 20, fat: 0,   serving: '½ cup' },
  { id: 'p32', name: 'Navy Beans',             category: 'Proteins',  calories: 127, protein: 8,  carbs: 24, fat: 1,   serving: '½ cup' },
  { id: 'p33', name: 'Seitan',                 category: 'Proteins',  calories: 370, protein: 75, carbs: 14, fat: 2,   serving: '100g' },
  { id: 'p34', name: 'Hemp Seeds',             category: 'Proteins',  calories: 166, protein: 10, carbs: 3,  fat: 14,  serving: '3 tbsp' },
  { id: 'p35', name: 'Protein Powder',         category: 'Proteins',  calories: 120, protein: 24, carbs: 3,  fat: 2,   serving: '1 scoop' },
  { id: 'p36', name: 'Bison',                  category: 'Proteins',  calories: 146, protein: 28, carbs: 0,  fat: 4,   serving: '100g' },
  { id: 'p37', name: 'Chicken Wings',          category: 'Proteins',  calories: 430, protein: 36, carbs: 0,  fat: 30,  serving: '4 wings' },
  { id: 'p38', name: 'Lobster',                category: 'Proteins',  calories: 89,  protein: 19, carbs: 0,  fat: 1,   serving: '100g' },
  { id: 'p39', name: 'Split Peas',             category: 'Proteins',  calories: 116, protein: 8,  carbs: 21, fat: 0,   serving: '½ cup cooked' },
  { id: 'p40', name: 'Venison',                category: 'Proteins',  calories: 158, protein: 26, carbs: 0,  fat: 6,   serving: '100g' },

  // ── Carbs & Grains ─────────────────────────────────────────────────────────
  { id: 'c1',  name: 'Brown Rice',             category: 'Carbs & Grains', calories: 215, protein: 5,  carbs: 45, fat: 2,  serving: '1 cup cooked' },
  { id: 'c2',  name: 'White Rice',             category: 'Carbs & Grains', calories: 205, protein: 4,  carbs: 45, fat: 0,  serving: '1 cup cooked' },
  { id: 'c3',  name: 'Pasta',                  category: 'Carbs & Grains', calories: 200, protein: 7,  carbs: 40, fat: 1,  serving: '1 cup cooked' },
  { id: 'c4',  name: 'Quinoa',                 category: 'Carbs & Grains', calories: 222, protein: 8,  carbs: 39, fat: 4,  serving: '1 cup cooked' },
  { id: 'c5',  name: 'Sweet Potato',           category: 'Carbs & Grains', calories: 103, protein: 2,  carbs: 24, fat: 0,  serving: '1 medium' },
  { id: 'c6',  name: 'White Potato',           category: 'Carbs & Grains', calories: 161, protein: 4,  carbs: 37, fat: 0,  serving: '1 medium' },
  { id: 'c7',  name: 'Whole Wheat Bread',      category: 'Carbs & Grains', calories: 80,  protein: 3,  carbs: 15, fat: 1,  serving: '1 slice' },
  { id: 'c8',  name: 'Flour Tortilla',         category: 'Carbs & Grains', calories: 90,  protein: 2,  carbs: 18, fat: 2,  serving: '1 medium' },
  { id: 'c9',  name: 'Couscous',               category: 'Carbs & Grains', calories: 176, protein: 6,  carbs: 36, fat: 0,  serving: '1 cup cooked' },
  { id: 'c10', name: 'Pita Bread',             category: 'Carbs & Grains', calories: 165, protein: 5,  carbs: 33, fat: 1,  serving: '1 medium' },
  { id: 'c11', name: 'Oat Bran',               category: 'Carbs & Grains', calories: 88,  protein: 7,  carbs: 25, fat: 2,  serving: '½ cup dry' },
  { id: 'c12', name: 'Barley',                 category: 'Carbs & Grains', calories: 193, protein: 4,  carbs: 44, fat: 1,  serving: '1 cup cooked' },
  { id: 'c13', name: 'Sourdough Bread',        category: 'Carbs & Grains', calories: 93,  protein: 4,  carbs: 18, fat: 1,  serving: '1 slice' },
  { id: 'c14', name: 'Corn Tortilla',          category: 'Carbs & Grains', calories: 52,  protein: 1,  carbs: 11, fat: 1,  serving: '1 medium' },
  { id: 'c15', name: 'White Bread',            category: 'Carbs & Grains', calories: 79,  protein: 3,  carbs: 15, fat: 1,  serving: '1 slice' },
  { id: 'c16', name: 'Naan Bread',             category: 'Carbs & Grains', calories: 262, protein: 9,  carbs: 45, fat: 5,  serving: '1 piece' },
  { id: 'c17', name: 'Rice Noodles',           category: 'Carbs & Grains', calories: 192, protein: 4,  carbs: 44, fat: 0,  serving: '1 cup cooked' },
  { id: 'c18', name: 'Buckwheat',              category: 'Carbs & Grains', calories: 155, protein: 6,  carbs: 33, fat: 1,  serving: '1 cup cooked' },
  { id: 'c19', name: 'Rye Bread',              category: 'Carbs & Grains', calories: 83,  protein: 3,  carbs: 15, fat: 1,  serving: '1 slice' },
  { id: 'c20', name: 'Crackers (whole grain)', category: 'Carbs & Grains', calories: 70,  protein: 1,  carbs: 11, fat: 3,  serving: '5 crackers' },
  { id: 'c21', name: 'Wild Rice',              category: 'Carbs & Grains', calories: 166, protein: 7,  carbs: 35, fat: 1,  serving: '1 cup cooked' },
  { id: 'c22', name: 'Farro',                  category: 'Carbs & Grains', calories: 220, protein: 8,  carbs: 46, fat: 2,  serving: '1 cup cooked' },
  { id: 'c23', name: 'Polenta',                category: 'Carbs & Grains', calories: 145, protein: 4,  carbs: 30, fat: 1,  serving: '1 cup' },
  { id: 'c24', name: 'Millet',                 category: 'Carbs & Grains', calories: 207, protein: 6,  carbs: 41, fat: 2,  serving: '1 cup cooked' },
  { id: 'c25', name: 'Soba Noodles',           category: 'Carbs & Grains', calories: 113, protein: 6,  carbs: 24, fat: 0,  serving: '1 cup cooked' },
  { id: 'c26', name: 'Udon Noodles',           category: 'Carbs & Grains', calories: 210, protein: 7,  carbs: 43, fat: 1,  serving: '1 cup cooked' },
  { id: 'c27', name: 'Egg Noodles',            category: 'Carbs & Grains', calories: 221, protein: 8,  carbs: 40, fat: 3,  serving: '1 cup cooked' },
  { id: 'c28', name: 'Gnocchi',                category: 'Carbs & Grains', calories: 248, protein: 6,  carbs: 52, fat: 2,  serving: '1 cup' },
  { id: 'c29', name: 'Pretzel',                category: 'Carbs & Grains', calories: 229, protein: 6,  carbs: 48, fat: 2,  serving: '1 large' },
  { id: 'c30', name: 'Pumpernickel Bread',     category: 'Carbs & Grains', calories: 80,  protein: 3,  carbs: 15, fat: 1,  serving: '1 slice' },
  { id: 'c31', name: 'Flatbread',              category: 'Carbs & Grains', calories: 120, protein: 3,  carbs: 22, fat: 3,  serving: '1 piece' },
  { id: 'c32', name: 'Whole Wheat Wrap',       category: 'Carbs & Grains', calories: 120, protein: 4,  carbs: 22, fat: 3,  serving: '1 medium' },
  { id: 'c33', name: 'Freekeh',                category: 'Carbs & Grains', calories: 190, protein: 8,  carbs: 42, fat: 1,  serving: '1 cup cooked' },
  { id: 'c34', name: 'Spelt Bread',            category: 'Carbs & Grains', calories: 90,  protein: 4,  carbs: 16, fat: 1,  serving: '1 slice' },
  { id: 'c35', name: 'Rice Cake',              category: 'Carbs & Grains', calories: 35,  protein: 1,  carbs: 7,  fat: 0,  serving: '1 cake' },
  { id: 'c36', name: 'Teff',                   category: 'Carbs & Grains', calories: 255, protein: 10, carbs: 50, fat: 2,  serving: '1 cup cooked' },
  { id: 'c37', name: 'Amaranth',               category: 'Carbs & Grains', calories: 251, protein: 9,  carbs: 46, fat: 4,  serving: '1 cup cooked' },
  { id: 'c38', name: 'Breadsticks',            category: 'Carbs & Grains', calories: 117, protein: 3,  carbs: 22, fat: 2,  serving: '3 sticks' },
  { id: 'c39', name: 'Jasmine Rice',           category: 'Carbs & Grains', calories: 205, protein: 4,  carbs: 45, fat: 0,  serving: '1 cup cooked' },
  { id: 'c40', name: 'French Baguette',        category: 'Carbs & Grains', calories: 162, protein: 6,  carbs: 31, fat: 1,  serving: '2 oz' },

  // ── Vegetables ─────────────────────────────────────────────────────────────
  { id: 'v1',  name: 'Broccoli',               category: 'Vegetables', calories: 55,  protein: 4,  carbs: 11, fat: 1,  serving: '1 cup' },
  { id: 'v2',  name: 'Spinach',                category: 'Vegetables', calories: 7,   protein: 1,  carbs: 1,  fat: 0,  serving: '1 cup raw' },
  { id: 'v3',  name: 'Mixed Green Salad',      category: 'Vegetables', calories: 20,  protein: 1,  carbs: 4,  fat: 0,  serving: '2 cups' },
  { id: 'v4',  name: 'Bell Pepper',            category: 'Vegetables', calories: 31,  protein: 1,  carbs: 7,  fat: 0,  serving: '1 medium' },
  { id: 'v5',  name: 'Carrots',                category: 'Vegetables', calories: 25,  protein: 1,  carbs: 6,  fat: 0,  serving: '1 medium' },
  { id: 'v6',  name: 'Cucumber',               category: 'Vegetables', calories: 16,  protein: 1,  carbs: 4,  fat: 0,  serving: '1 cup sliced' },
  { id: 'v7',  name: 'Tomato',                 category: 'Vegetables', calories: 22,  protein: 1,  carbs: 5,  fat: 0,  serving: '1 medium' },
  { id: 'v8',  name: 'Zucchini',               category: 'Vegetables', calories: 21,  protein: 2,  carbs: 4,  fat: 0,  serving: '1 cup' },
  { id: 'v9',  name: 'Kale',                   category: 'Vegetables', calories: 33,  protein: 2,  carbs: 7,  fat: 1,  serving: '1 cup raw' },
  { id: 'v10', name: 'Asparagus',              category: 'Vegetables', calories: 27,  protein: 3,  carbs: 5,  fat: 0,  serving: '1 cup' },
  { id: 'v11', name: 'Cauliflower',            category: 'Vegetables', calories: 25,  protein: 2,  carbs: 5,  fat: 0,  serving: '1 cup' },
  { id: 'v12', name: 'Green Beans',            category: 'Vegetables', calories: 31,  protein: 2,  carbs: 7,  fat: 0,  serving: '1 cup' },
  { id: 'v13', name: 'Mushrooms',              category: 'Vegetables', calories: 21,  protein: 3,  carbs: 3,  fat: 0,  serving: '1 cup' },
  { id: 'v14', name: 'Sweet Corn',             category: 'Vegetables', calories: 132, protein: 5,  carbs: 29, fat: 2,  serving: '1 cup' },
  { id: 'v15', name: 'Peas',                   category: 'Vegetables', calories: 62,  protein: 4,  carbs: 11, fat: 0,  serving: '½ cup' },
  { id: 'v16', name: 'Brussels Sprouts',       category: 'Vegetables', calories: 56,  protein: 4,  carbs: 11, fat: 1,  serving: '1 cup' },
  { id: 'v17', name: 'Beets',                  category: 'Vegetables', calories: 43,  protein: 2,  carbs: 10, fat: 0,  serving: '1 medium' },
  { id: 'v18', name: 'Eggplant',               category: 'Vegetables', calories: 35,  protein: 1,  carbs: 9,  fat: 0,  serving: '1 cup' },
  { id: 'v19', name: 'Celery',                 category: 'Vegetables', calories: 12,  protein: 1,  carbs: 2,  fat: 0,  serving: '2 stalks' },
  { id: 'v20', name: 'Onion',                  category: 'Vegetables', calories: 44,  protein: 1,  carbs: 10, fat: 0,  serving: '1 medium' },
  { id: 'v21', name: 'Artichoke',              category: 'Vegetables', calories: 60,  protein: 4,  carbs: 13, fat: 0,  serving: '1 medium' },
  { id: 'v22', name: 'Bok Choy',               category: 'Vegetables', calories: 9,   protein: 1,  carbs: 2,  fat: 0,  serving: '1 cup' },
  { id: 'v23', name: 'Butternut Squash',       category: 'Vegetables', calories: 82,  protein: 2,  carbs: 22, fat: 0,  serving: '1 cup' },
  { id: 'v24', name: 'Cabbage',                category: 'Vegetables', calories: 22,  protein: 1,  carbs: 5,  fat: 0,  serving: '1 cup shredded' },
  { id: 'v25', name: 'Snow Peas',              category: 'Vegetables', calories: 41,  protein: 3,  carbs: 7,  fat: 0,  serving: '1 cup' },
  { id: 'v26', name: 'Romaine Lettuce',        category: 'Vegetables', calories: 8,   protein: 1,  carbs: 1,  fat: 0,  serving: '1 cup' },
  { id: 'v27', name: 'Cherry Tomatoes',        category: 'Vegetables', calories: 27,  protein: 1,  carbs: 6,  fat: 0,  serving: '1 cup' },
  { id: 'v28', name: 'Leeks',                  category: 'Vegetables', calories: 54,  protein: 1,  carbs: 13, fat: 0,  serving: '1 medium' },
  { id: 'v29', name: 'Swiss Chard',            category: 'Vegetables', calories: 7,   protein: 1,  carbs: 1,  fat: 0,  serving: '1 cup raw' },
  { id: 'v30', name: 'Collard Greens',         category: 'Vegetables', calories: 11,  protein: 1,  carbs: 2,  fat: 0,  serving: '1 cup raw' },
  { id: 'v31', name: 'Fennel',                 category: 'Vegetables', calories: 73,  protein: 3,  carbs: 17, fat: 0,  serving: '1 medium' },
  { id: 'v32', name: 'Parsnip',                category: 'Vegetables', calories: 100, protein: 2,  carbs: 24, fat: 0,  serving: '1 medium' },
  { id: 'v33', name: 'Radishes',               category: 'Vegetables', calories: 19,  protein: 1,  carbs: 4,  fat: 0,  serving: '1 cup' },
  { id: 'v34', name: 'Arugula',                category: 'Vegetables', calories: 5,   protein: 1,  carbs: 1,  fat: 0,  serving: '1 cup' },
  { id: 'v35', name: 'Garlic',                 category: 'Vegetables', calories: 13,  protein: 1,  carbs: 3,  fat: 0,  serving: '3 cloves' },
  { id: 'v36', name: 'Acorn Squash',           category: 'Vegetables', calories: 115, protein: 2,  carbs: 30, fat: 0,  serving: '1 cup' },
  { id: 'v37', name: 'Watercress',             category: 'Vegetables', calories: 4,   protein: 1,  carbs: 0,  fat: 0,  serving: '1 cup' },
  { id: 'v38', name: 'Turnip',                 category: 'Vegetables', calories: 34,  protein: 1,  carbs: 8,  fat: 0,  serving: '1 medium' },
  { id: 'v39', name: 'Edamame (shelled)',      category: 'Vegetables', calories: 94,  protein: 9,  carbs: 7,  fat: 4,  serving: '½ cup' },
  { id: 'v40', name: 'Jicama',                 category: 'Vegetables', calories: 46,  protein: 1,  carbs: 11, fat: 0,  serving: '1 cup' },

  // ── Fruits ─────────────────────────────────────────────────────────────────
  { id: 'f1',  name: 'Banana',                 category: 'Fruits',    calories: 105, protein: 1,  carbs: 27, fat: 0,  serving: '1 medium' },
  { id: 'f2',  name: 'Apple',                  category: 'Fruits',    calories: 95,  protein: 0,  carbs: 25, fat: 0,  serving: '1 medium' },
  { id: 'f3',  name: 'Orange',                 category: 'Fruits',    calories: 62,  protein: 1,  carbs: 15, fat: 0,  serving: '1 medium' },
  { id: 'f4',  name: 'Strawberries',           category: 'Fruits',    calories: 49,  protein: 1,  carbs: 12, fat: 1,  serving: '1 cup' },
  { id: 'f5',  name: 'Blueberries',            category: 'Fruits',    calories: 84,  protein: 1,  carbs: 21, fat: 1,  serving: '1 cup' },
  { id: 'f6',  name: 'Mango',                  category: 'Fruits',    calories: 107, protein: 1,  carbs: 25, fat: 1,  serving: '1 cup' },
  { id: 'f7',  name: 'Grapes',                 category: 'Fruits',    calories: 104, protein: 1,  carbs: 27, fat: 0,  serving: '1 cup' },
  { id: 'f8',  name: 'Watermelon',             category: 'Fruits',    calories: 46,  protein: 1,  carbs: 12, fat: 0,  serving: '1 cup' },
  { id: 'f9',  name: 'Pineapple',              category: 'Fruits',    calories: 82,  protein: 1,  carbs: 22, fat: 0,  serving: '1 cup' },
  { id: 'f10', name: 'Avocado',                category: 'Fruits',    calories: 120, protein: 2,  carbs: 6,  fat: 11, serving: '½ medium' },
  { id: 'f11', name: 'Raspberries',            category: 'Fruits',    calories: 64,  protein: 1,  carbs: 15, fat: 1,  serving: '1 cup' },
  { id: 'f12', name: 'Peach',                  category: 'Fruits',    calories: 58,  protein: 1,  carbs: 14, fat: 0,  serving: '1 medium' },
  { id: 'f13', name: 'Kiwi',                   category: 'Fruits',    calories: 42,  protein: 1,  carbs: 10, fat: 0,  serving: '1 medium' },
  { id: 'f14', name: 'Pear',                   category: 'Fruits',    calories: 101, protein: 1,  carbs: 27, fat: 0,  serving: '1 medium' },
  { id: 'f15', name: 'Cherries',               category: 'Fruits',    calories: 87,  protein: 1,  carbs: 22, fat: 0,  serving: '1 cup' },
  { id: 'f16', name: 'Grapefruit',             category: 'Fruits',    calories: 41,  protein: 1,  carbs: 10, fat: 0,  serving: '½ medium' },
  { id: 'f17', name: 'Pomegranate Seeds',      category: 'Fruits',    calories: 72,  protein: 1,  carbs: 16, fat: 1,  serving: '½ cup' },
  { id: 'f18', name: 'Dates',                  category: 'Fruits',    calories: 100, protein: 1,  carbs: 27, fat: 0,  serving: '3 dates' },
  { id: 'f19', name: 'Cantaloupe',             category: 'Fruits',    calories: 53,  protein: 1,  carbs: 13, fat: 0,  serving: '1 cup' },
  { id: 'f20', name: 'Papaya',                 category: 'Fruits',    calories: 55,  protein: 1,  carbs: 14, fat: 0,  serving: '1 cup' },
  { id: 'f21', name: 'Lychee',                 category: 'Fruits',    calories: 125, protein: 1,  carbs: 31, fat: 1,  serving: '1 cup' },
  { id: 'f22', name: 'Dragon Fruit',           category: 'Fruits',    calories: 102, protein: 2,  carbs: 22, fat: 0,  serving: '1 cup' },
  { id: 'f23', name: 'Plum',                   category: 'Fruits',    calories: 30,  protein: 0,  carbs: 8,  fat: 0,  serving: '1 medium' },
  { id: 'f24', name: 'Nectarine',              category: 'Fruits',    calories: 62,  protein: 1,  carbs: 15, fat: 0,  serving: '1 medium' },
  { id: 'f25', name: 'Figs (fresh)',           category: 'Fruits',    calories: 74,  protein: 1,  carbs: 19, fat: 0,  serving: '2 medium' },
  { id: 'f26', name: 'Guava',                  category: 'Fruits',    calories: 37,  protein: 1,  carbs: 8,  fat: 1,  serving: '1 medium' },
  { id: 'f27', name: 'Passion Fruit',          category: 'Fruits',    calories: 97,  protein: 2,  carbs: 23, fat: 1,  serving: '100g' },
  { id: 'f28', name: 'Jackfruit',              category: 'Fruits',    calories: 155, protein: 3,  carbs: 40, fat: 1,  serving: '1 cup' },
  { id: 'f29', name: 'Blackberries',           category: 'Fruits',    calories: 62,  protein: 2,  carbs: 14, fat: 1,  serving: '1 cup' },
  { id: 'f30', name: 'Apricot',                category: 'Fruits',    calories: 50,  protein: 1,  carbs: 12, fat: 0,  serving: '3 medium' },
  { id: 'f31', name: 'Clementine',             category: 'Fruits',    calories: 35,  protein: 1,  carbs: 9,  fat: 0,  serving: '1 medium' },
  { id: 'f32', name: 'Honeydew',               category: 'Fruits',    calories: 61,  protein: 1,  carbs: 15, fat: 0,  serving: '1 cup' },
  { id: 'f33', name: 'Tangerine',              category: 'Fruits',    calories: 47,  protein: 1,  carbs: 12, fat: 0,  serving: '1 medium' },
  { id: 'f34', name: 'Persimmon',              category: 'Fruits',    calories: 118, protein: 1,  carbs: 31, fat: 0,  serving: '1 medium' },
  { id: 'f35', name: 'Cranberries',            category: 'Fruits',    calories: 46,  protein: 0,  carbs: 12, fat: 0,  serving: '1 cup' },
  { id: 'f36', name: 'Mulberries',             category: 'Fruits',    calories: 60,  protein: 2,  carbs: 14, fat: 1,  serving: '1 cup' },
  { id: 'f37', name: 'Coconut Meat',           category: 'Fruits',    calories: 283, protein: 3,  carbs: 12, fat: 27, serving: '1 cup shredded' },
  { id: 'f38', name: 'Star Fruit',             category: 'Fruits',    calories: 28,  protein: 1,  carbs: 6,  fat: 0,  serving: '1 medium' },
  { id: 'f39', name: 'Boysenberries',          category: 'Fruits',    calories: 66,  protein: 1,  carbs: 16, fat: 0,  serving: '1 cup' },
  { id: 'f40', name: 'Lime',                   category: 'Fruits',    calories: 20,  protein: 0,  carbs: 7,  fat: 0,  serving: '1 medium' },

  // ── Dairy & Snacks ─────────────────────────────────────────────────────────
  { id: 'd1',  name: 'Whole Milk',             category: 'Dairy & Snacks', calories: 150, protein: 8,  carbs: 12, fat: 8,  serving: '1 cup' },
  { id: 'd2',  name: 'Cheddar Cheese',         category: 'Dairy & Snacks', calories: 110, protein: 7,  carbs: 0,  fat: 9,  serving: '1 oz' },
  { id: 'd3',  name: 'Almonds',                category: 'Dairy & Snacks', calories: 164, protein: 6,  carbs: 6,  fat: 14, serving: '1 oz (23 nuts)' },
  { id: 'd4',  name: 'Peanut Butter',          category: 'Dairy & Snacks', calories: 190, protein: 8,  carbs: 6,  fat: 16, serving: '2 tbsp' },
  { id: 'd5',  name: 'Hummus',                 category: 'Dairy & Snacks', calories: 50,  protein: 2,  carbs: 6,  fat: 3,  serving: '2 tbsp' },
  { id: 'd6',  name: 'Rice Cakes',             category: 'Dairy & Snacks', calories: 70,  protein: 1,  carbs: 15, fat: 0,  serving: '2 cakes' },
  { id: 'd7',  name: 'Protein Bar',            category: 'Dairy & Snacks', calories: 200, protein: 20, carbs: 22, fat: 7,  serving: '1 bar' },
  { id: 'd8',  name: 'Dark Chocolate',         category: 'Dairy & Snacks', calories: 170, protein: 2,  carbs: 14, fat: 12, serving: '1 oz' },
  { id: 'd9',  name: 'String Cheese',          category: 'Dairy & Snacks', calories: 80,  protein: 7,  carbs: 0,  fat: 6,  serving: '1 stick' },
  { id: 'd10', name: 'Low-Fat Greek Yogurt',   category: 'Dairy & Snacks', calories: 100, protein: 17, carbs: 6,  fat: 0,  serving: '1 cup' },
  { id: 'd11', name: 'Cashews',                category: 'Dairy & Snacks', calories: 157, protein: 5,  carbs: 9,  fat: 12, serving: '1 oz' },
  { id: 'd12', name: 'Skim Milk',              category: 'Dairy & Snacks', calories: 83,  protein: 8,  carbs: 12, fat: 0,  serving: '1 cup' },
  { id: 'd13', name: 'Mozzarella',             category: 'Dairy & Snacks', calories: 85,  protein: 6,  carbs: 1,  fat: 6,  serving: '1 oz' },
  { id: 'd14', name: 'Walnuts',                category: 'Dairy & Snacks', calories: 185, protein: 4,  carbs: 4,  fat: 18, serving: '1 oz' },
  { id: 'd15', name: 'Popcorn (air-popped)',   category: 'Dairy & Snacks', calories: 93,  protein: 3,  carbs: 19, fat: 1,  serving: '3 cups' },
  { id: 'd16', name: 'Granola Bar',            category: 'Dairy & Snacks', calories: 190, protein: 4,  carbs: 28, fat: 7,  serving: '1 bar' },
  { id: 'd17', name: 'Kefir',                  category: 'Dairy & Snacks', calories: 110, protein: 11, carbs: 12, fat: 2,  serving: '1 cup' },
  { id: 'd18', name: 'Trail Mix',              category: 'Dairy & Snacks', calories: 131, protein: 4,  carbs: 13, fat: 8,  serving: '1 oz' },
  { id: 'd19', name: 'Almond Milk',            category: 'Dairy & Snacks', calories: 40,  protein: 1,  carbs: 3,  fat: 3,  serving: '1 cup' },
  { id: 'd20', name: 'Sunflower Seeds',        category: 'Dairy & Snacks', calories: 166, protein: 5,  carbs: 7,  fat: 14, serving: '1 oz' },
  { id: 'd21', name: 'Pistachios',             category: 'Dairy & Snacks', calories: 159, protein: 6,  carbs: 8,  fat: 13, serving: '1 oz' },
  { id: 'd22', name: 'Pecans',                 category: 'Dairy & Snacks', calories: 196, protein: 3,  carbs: 4,  fat: 20, serving: '1 oz' },
  { id: 'd23', name: 'Pumpkin Seeds',          category: 'Dairy & Snacks', calories: 151, protein: 7,  carbs: 5,  fat: 13, serving: '1 oz' },
  { id: 'd24', name: 'Feta Cheese',            category: 'Dairy & Snacks', calories: 75,  protein: 4,  carbs: 1,  fat: 6,  serving: '1 oz' },
  { id: 'd25', name: 'Parmesan',               category: 'Dairy & Snacks', calories: 43,  protein: 4,  carbs: 0,  fat: 3,  serving: '2 tbsp' },
  { id: 'd26', name: 'Brie',                   category: 'Dairy & Snacks', calories: 95,  protein: 6,  carbs: 0,  fat: 8,  serving: '1 oz' },
  { id: 'd27', name: 'Oat Milk',               category: 'Dairy & Snacks', calories: 120, protein: 3,  carbs: 16, fat: 5,  serving: '1 cup' },
  { id: 'd28', name: 'Chocolate Milk',         category: 'Dairy & Snacks', calories: 208, protein: 8,  carbs: 26, fat: 8,  serving: '1 cup' },
  { id: 'd29', name: 'Pretzels',               category: 'Dairy & Snacks', calories: 110, protein: 3,  carbs: 23, fat: 1,  serving: '1 oz' },
  { id: 'd30', name: 'Potato Chips',           category: 'Dairy & Snacks', calories: 152, protein: 2,  carbs: 15, fat: 10, serving: '1 oz' },
  { id: 'd31', name: 'Rice Pudding',           category: 'Dairy & Snacks', calories: 155, protein: 4,  carbs: 30, fat: 2,  serving: '½ cup' },
  { id: 'd32', name: 'Macadamia Nuts',         category: 'Dairy & Snacks', calories: 204, protein: 2,  carbs: 4,  fat: 21, serving: '1 oz' },
  { id: 'd33', name: 'Pine Nuts',              category: 'Dairy & Snacks', calories: 191, protein: 4,  carbs: 4,  fat: 19, serving: '1 oz' },
  { id: 'd34', name: 'Gouda Cheese',           category: 'Dairy & Snacks', calories: 101, protein: 7,  carbs: 1,  fat: 8,  serving: '1 oz' },
  { id: 'd35', name: 'Ricotta Cheese',         category: 'Dairy & Snacks', calories: 214, protein: 14, carbs: 4,  fat: 16, serving: '½ cup' },
  { id: 'd36', name: 'Butter',                 category: 'Dairy & Snacks', calories: 102, protein: 0,  carbs: 0,  fat: 12, serving: '1 tbsp' },
  { id: 'd37', name: 'Sour Cream',             category: 'Dairy & Snacks', calories: 60,  protein: 1,  carbs: 1,  fat: 6,  serving: '2 tbsp' },
  { id: 'd38', name: 'Coconut Yogurt',         category: 'Dairy & Snacks', calories: 150, protein: 1,  carbs: 17, fat: 8,  serving: '¾ cup' },
  { id: 'd39', name: 'Chocolate Bar (milk)',   category: 'Dairy & Snacks', calories: 235, protein: 3,  carbs: 26, fat: 13, serving: '1.5 oz' },
  { id: 'd40', name: 'Energy Bites',           category: 'Dairy & Snacks', calories: 180, protein: 5,  carbs: 22, fat: 8,  serving: '2 bites' },

  // ── Meals ──────────────────────────────────────────────────────────────────
  { id: 'm1',  name: 'Burger',                 category: 'Meals',     calories: 450, protein: 25, carbs: 40, fat: 20, serving: '1 medium' },
  { id: 'm2',  name: 'Chicken Sandwich',       category: 'Meals',     calories: 400, protein: 30, carbs: 38, fat: 15, serving: '1 sandwich' },
  { id: 'm3',  name: 'Caesar Salad',           category: 'Meals',     calories: 350, protein: 15, carbs: 20, fat: 25, serving: '1 serving' },
  { id: 'm4',  name: 'Burrito Bowl',           category: 'Meals',     calories: 650, protein: 35, carbs: 70, fat: 22, serving: '1 bowl' },
  { id: 'm5',  name: 'Veggie Stir Fry',        category: 'Meals',     calories: 300, protein: 20, carbs: 25, fat: 12, serving: '1 cup' },
  { id: 'm6',  name: 'Sushi (8 pieces)',       category: 'Meals',     calories: 320, protein: 15, carbs: 58, fat: 4,  serving: '8 pieces' },
  { id: 'm7',  name: 'Pizza Slice',            category: 'Meals',     calories: 285, protein: 12, carbs: 36, fat: 10, serving: '1 slice' },
  { id: 'm8',  name: 'Vegetable Soup',         category: 'Meals',     calories: 80,  protein: 4,  carbs: 15, fat: 1,  serving: '1 cup' },
  { id: 'm9',  name: 'Tacos',                  category: 'Meals',     calories: 350, protein: 20, carbs: 30, fat: 15, serving: '2 corn tacos' },
  { id: 'm10', name: 'Grilled Chicken Salad',  category: 'Meals',     calories: 300, protein: 35, carbs: 15, fat: 12, serving: '1 serving' },
  { id: 'm11', name: 'Salmon Bowl',            category: 'Meals',     calories: 480, protein: 32, carbs: 45, fat: 16, serving: '1 bowl' },
  { id: 'm12', name: 'Turkey Wrap',            category: 'Meals',     calories: 380, protein: 28, carbs: 35, fat: 12, serving: '1 wrap' },
  { id: 'm13', name: 'Chicken Fried Rice',     category: 'Meals',     calories: 400, protein: 20, carbs: 50, fat: 12, serving: '1 cup' },
  { id: 'm14', name: 'Pad Thai',               category: 'Meals',     calories: 450, protein: 22, carbs: 55, fat: 15, serving: '1 serving' },
  { id: 'm15', name: 'Lentil Soup',            category: 'Meals',     calories: 230, protein: 16, carbs: 38, fat: 3,  serving: '1 cup' },
  { id: 'm16', name: 'Fish Tacos',             category: 'Meals',     calories: 370, protein: 25, carbs: 35, fat: 14, serving: '2 tacos' },
  { id: 'm17', name: 'Chicken Tikka Masala',   category: 'Meals',     calories: 320, protein: 28, carbs: 15, fat: 15, serving: '1 cup' },
  { id: 'm18', name: 'Poke Bowl',              category: 'Meals',     calories: 520, protein: 30, carbs: 60, fat: 15, serving: '1 bowl' },
  { id: 'm19', name: 'Shakshuka',              category: 'Meals',     calories: 280, protein: 18, carbs: 20, fat: 15, serving: '1 serving' },
  { id: 'm20', name: 'Chicken Noodle Soup',    category: 'Meals',     calories: 175, protein: 12, carbs: 20, fat: 4,  serving: '1 cup' },
  { id: 'm21', name: 'Pasta Bolognese',        category: 'Meals',     calories: 450, protein: 25, carbs: 50, fat: 15, serving: '1 cup' },
  { id: 'm22', name: 'Beef Stew',              category: 'Meals',     calories: 280, protein: 22, carbs: 20, fat: 12, serving: '1 cup' },
  { id: 'm23', name: 'Chili (beef)',           category: 'Meals',     calories: 350, protein: 28, carbs: 25, fat: 14, serving: '1 cup' },
  { id: 'm24', name: 'Ramen',                  category: 'Meals',     calories: 530, protein: 22, carbs: 60, fat: 22, serving: '1 bowl' },
  { id: 'm25', name: 'Falafel Wrap',           category: 'Meals',     calories: 450, protein: 16, carbs: 55, fat: 18, serving: '1 wrap' },
  { id: 'm26', name: 'Bibimbap',               category: 'Meals',     calories: 550, protein: 25, carbs: 65, fat: 18, serving: '1 bowl' },
  { id: 'm27', name: 'Chicken Quesadilla',     category: 'Meals',     calories: 490, protein: 30, carbs: 42, fat: 20, serving: '1 quesadilla' },
  { id: 'm28', name: 'Mac & Cheese',           category: 'Meals',     calories: 310, protein: 12, carbs: 40, fat: 12, serving: '1 cup' },
  { id: 'm29', name: 'Minestrone Soup',        category: 'Meals',     calories: 130, protein: 6,  carbs: 22, fat: 2,  serving: '1 cup' },
  { id: 'm30', name: 'Lamb Gyro',              category: 'Meals',     calories: 450, protein: 28, carbs: 40, fat: 18, serving: '1 pita' },
  { id: 'm31', name: 'Veggie Burger',          category: 'Meals',     calories: 380, protein: 22, carbs: 40, fat: 14, serving: '1 burger' },
  { id: 'm32', name: 'Spaghetti Bolognese',    category: 'Meals',     calories: 450, protein: 25, carbs: 50, fat: 15, serving: '1 serving' },
  { id: 'm33', name: 'Shrimp Scampi',          category: 'Meals',     calories: 380, protein: 28, carbs: 30, fat: 18, serving: '1 serving' },
  { id: 'm34', name: 'Greek Salad',            category: 'Meals',     calories: 185, protein: 5,  carbs: 10, fat: 14, serving: '1 serving' },
  { id: 'm35', name: 'Chicken Fajitas',        category: 'Meals',     calories: 420, protein: 32, carbs: 38, fat: 15, serving: '1 serving' },
  { id: 'm36', name: 'Egg Fried Rice',         category: 'Meals',     calories: 330, protein: 12, carbs: 45, fat: 10, serving: '1 cup' },
  { id: 'm37', name: 'Tom Yum Soup',           category: 'Meals',     calories: 150, protein: 12, carbs: 10, fat: 7,  serving: '1 cup' },
  { id: 'm38', name: 'Chicken Pesto Pasta',    category: 'Meals',     calories: 480, protein: 32, carbs: 45, fat: 18, serving: '1 cup' },
  { id: 'm39', name: 'Beef Bulgogi Bowl',      category: 'Meals',     calories: 480, protein: 30, carbs: 50, fat: 15, serving: '1 bowl' },
  { id: 'm40', name: 'Pasta Carbonara',        category: 'Meals',     calories: 500, protein: 20, carbs: 55, fat: 22, serving: '1 cup' },
];

export const genId = () =>
  `${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
